name: Testing

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
        gql-version: [ 2, 3 ]
        include:
          - graphene-version: '>=2.1.0,<3'
            graphene-tests: graphene_2
            gql-version: 2
          - graphene-version: '>=3,<4'
            graphene-tests: graphene_3
            gql-version: 3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'graphene${{ matrix.graphene-version }}'
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover -s $(pwd)/tests/common -t $(pwd)
          python -m unittest discover -s $(pwd)/tests/${{ matrix.graphene-tests }} -t $(pwd)
