name: Testing

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
        multiple-versions: [ 'on' ]
        include:
          - graphql-core-version: '>=2.1.0,<3'
            graphene-tests: graphene_2
            multiple-versions: 'on'
          - graphql-core-version: '>=3.1.5,<4'
            graphene-tests: graphene_3
            multiple-versions: 'on'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ matrix.graphql-core-version }}
          pip install -f requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover -s $(pwd)/tests/common -t $(pwd)
          python -m unittest discover -s $(pwd)/tests/${{ matrix.graphene-tests }} -t $(pwd)
